const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const path = require('path');
const crypto = require('crypto');
const fs = require('fs');

const app = express();
const server = http.createServer(app);
const io = new Server(server);
app.use(express.static(path.join(__dirname, 'public')));
app.use('/three', express.static(path.join(__dirname, 'node_modules', 'three', 'build')));
app.use('/three-addons', express.static(path.join(__dirname, 'node_modules', 'three', 'examples', 'jsm')));

const rooms = new Map();
const DATA_DIR=path.join(__dirname,'data'),ROOMS_FILE=process.env.ROOMS_FILE||path.join(DATA_DIR,'rooms.json');
function persistRooms(){try{fs.mkdirSync(path.dirname(ROOMS_FILE),{recursive:true});const temporary=`${ROOMS_FILE}.tmp`;fs.writeFileSync(temporary,JSON.stringify([...rooms.values()],null,2),'utf8');fs.renameSync(temporary,ROOMS_FILE)}catch(error){console.error('No se pudieron guardar las salas:',error.message)}}
function restoreRooms(){try{if(!fs.existsSync(ROOMS_FILE))return;const saved=JSON.parse(fs.readFileSync(ROOMS_FILE,'utf8'));if(!Array.isArray(saved))return;saved.forEach(room=>{if(!room?.code||!Array.isArray(room.players))return;room.players.forEach(player=>{player.connected=false;player.connectionId=null;statsOf(player)});room.chatMessages=room.chatMessages||[];room.log=room.log||[];room.offers=room.offers||[];room.debts=room.debts||[];room.buildings=room.buildings||{};room.mortgages=room.mortgages||{};roomSettings(room);rooms.set(room.code,room);if(room.status==='playing')pauseTurnForDisconnect(room)});console.log(`${rooms.size} sala(s) restaurada(s).`)}catch(error){console.error('No se pudieron restaurar las salas:',error.message)}}
const COLORS = ['#ff6b55', '#2f80ed', '#27ae60', '#9b51e0', '#f2c94c', '#eb5757'];
const TOKENS = ['cat','frog','flower','block','plane','globe','owl','wartortle'];
const round500=value=>Math.max(500,Math.round(value/500)*500);
const REFERENCE_RENTS={
  24000:[3000,9500,26000,72000,96000,120000],
  28000:[3000,11500,30500,84000,112000,140000],
  38000:[4500,15500,41500,114000,152000,190000]
};
const property=(name,price,group)=>{const rents=REFERENCE_RENTS[price]||[.12,.4,1.1,3,4,5].map(rate=>round500(price*rate)),houseCost=Math.max(5000,Math.round((price*.5)/5000)*5000);return{type:'property',name,price,group,rent:rents[0],mortgage:price/2,houseCost,hotelCost:houseCost,rents}};
const airline=name=>({type:'transport',name,price:20000});
const BOARD = [
  {type:'start',name:'SALIDA'},
  property('Marruecos',12000,'africa'), property('Egipto',15000,'africa'),
  {type:'diplomatic',name:'Embajada',price:20000}, property('Sudáfrica',23000,'africa'),
  airline('Aerolínea Afroasiática'), property('Rusia',24000,'asia'), property('China',28000,'asia'),
  {type:'email',name:'Mensaje'}, property('Japón',38000,'asia'), {type:'jail',name:'DEPORTADO'},
  property('Canadá',30000,'northAmerica'), property('Estados Unidos',40000,'northAmerica'), {type:'fax',name:'Correo'},
  property('México',26000,'northAmerica'), airline('Aerolínea Norteamericana'), property('Guatemala',10000,'centralAmerica'),
  property('Costa Rica',10000,'centralAmerica'), {type:'email',name:'Mensaje'}, property('Panamá',8000,'centralAmerica'),
  {type:'rest',name:'AUSTRALIA'}, property('Colombia',20000,'northSouthAmerica'), {type:'diplomatic',name:'Consulado',price:20000},
  property('Venezuela',20000,'northSouthAmerica'), property('Perú',18000,'northSouthAmerica'), airline('Aerolínea Sudamericana'),
  property('Brasil',26000,'southSouthAmerica'), {type:'fax',name:'Correo'}, property('Chile',18000,'southSouthAmerica'),
  property('Argentina',25000,'southSouthAmerica'), {type:'goJail',name:'PASE A DEPORTADO'},
  property('España',28000,'westEurope'), property('Francia',36000,'westEurope'), {type:'fax',name:'Correo'},
  property('Inglaterra',32000,'westEurope'), airline('Aerolínea Europea'), property('Italia',35000,'eastEurope'),
  {type:'email',name:'Mensaje'}, property('Suiza',36000,'eastEurope'), property('Alemania',37000,'eastEurope')
];
const CARD_DECKS={fax:[
  {title:'Carta de expropiación',text:'Conserva esta carta. Podrás usarla para completar un bloque comprando una propiedad ocupada bajo sus condiciones.',keep:'expropriation'},
  {title:'Recupera tu pasaporte',text:'Conserva esta carta para salir inmediatamente de Deportado.',keep:'passport'},
  {title:'Intercambio cultural',text:'Conserva esta carta. Durante tu turno podrás intercambiar una propiedad sin construcciones ni hipoteca con otro jugador.',keep:'propertySwap'},
  {title:'Seguro de mantenimiento',text:'Conserva esta carta. Cancelará automáticamente tu siguiente pago de reparaciones por casas y hoteles.',keep:'repairInsurance'},
  {title:'Temporada alta',text:'Conserva esta carta. Actívala y la siguiente renta que cobres será doble.',keep:'rentBoost'},
  {title:'Reembolso internacional',text:'El banco te devuelve $10,000.',money:10000},
  {title:'Impuesto aeroportuario',text:'Paga $5,000 al banco.',money:-5000},
  {title:'Regreso a casa',text:'Avanza hasta la Salida y recibe $20,000.',start:true},
  {title:'Equipaje recuperado',text:'Recibes una compensación de $7,500.',money:7500},
  {title:'Multa de aduana',text:'Paga $4,000 por artículos no declarados.',money:-4000},
  {title:'Premio al viajero',text:'El banco te entrega $5,000.',money:5000},
  {title:'Visa aprobada en tiempo récord',text:'El consulado quedó impresionado con tu fotografía. Recibes $6,000 para tu siguiente aventura.',money:6000},
  {title:'Maleta con vida propia',text:'Tu equipaje viajó por tres países sin ti. La aerolínea paga $9,000 por la divertida confusión.',money:9000},
  {title:'Souvenirs sospechosamente brillantes',text:'Aduana decidió que tus recuerdos eran demasiado extravagantes. Paga $3,500.',money:-3500},
  {title:'Festival internacional',text:'Tu improvisado baile se volvió la sensación del festival. Cobra $7,000.',money:7000},
  {title:'Cambio de moneda desafortunado',text:'Confundiste la tasa de cambio y tu cartera lo resintió. Paga $4,500.',money:-4500},
  {title:'Seguro de viaje al rescate',text:'Encontraste aquel recibo arrugado que nadie creía útil. La aseguradora te paga $8,500.',money:8500},
  {title:'Cena en la embajada',text:'Fuiste invitado de honor, pero rompiste accidentalmente una lámpara histórica. Paga $5,500.',money:-5500},
  {title:'Beca para exploradores',text:'Tu bitácora inspiró a futuros viajeros. Recibes una beca de $12,000.',money:12000},
  {title:'Mantenimiento internacional',text:'Paga $2,000 por cada casa y $7,500 por cada hotel que poseas.',buildingFee:{house:-2000,hotel:-7500}},
  {title:'Premio de arquitectura',text:'Tus destinos fueron premiados: cobra $1,500 por cada casa y $5,000 por cada hotel.',buildingFee:{house:1500,hotel:5000}},
  {title:'Patrocinador de viaje',text:'Elige a un jugador para que patrocine tu próxima escala con $5,000.',choosePlayer:{amount:5000}}
  ,{title:'Vuelo directo a Japón',text:'Viaja inmediatamente a Japón. Si pasas por Salida, cobra $20,000.',moveTo:9}
  ,{title:'Recepción en España',text:'Avanza hasta España para una recepción internacional. Cobra Salida si corresponde.',moveTo:31}
  ,{title:'Error en la puerta de embarque',text:'Retrocede 3 casillas y resuelve el destino al que llegues.',moveSteps:-3}
  ,{title:'Conexión afroasiática',text:'Avanza hasta la Aerolínea Afroasiática.',moveTo:5}
  ,{title:'Cena para toda la delegación',text:'Paga $2,000 a cada jugador por la cena diplomática.',payEach:2000}
],email:[
  {title:'Mensaje nuevo: La vaquita',text:'Tus amigos organizaron una colecta: paga $1,000 a cada jugador.',payEach:1000},
  {title:'Apuesta en las cataratas',text:'Cobra $10,000 a cada jugador, pero perderás tu siguiente turno.',collectEach:10000,loseTurn:true},
  {title:'Fotografía premiada',text:'Tu fotografía ganó un concurso. Cobra $8,000.',money:8000},
  {title:'Reservación cancelada',text:'El hotel te cobra una penalización de $6,000.',money:-6000},
  {title:'Conducta inapropiada',text:'Las autoridades te envían directamente a Deportado.',goJail:true},
  {title:'Trabajo temporal',text:'Recibes $5,000 por ayudar en una feria internacional.',money:5000},
  {title:'Llamadas internacionales',text:'Paga una factura de $3,000.',money:-3000},
  {title:'Concurso de cultura',text:'Ganaste el concurso. Cobra $10,000.',money:10000},
  {title:'Tu video se hizo viral',text:'El video de tu intento por pedir comida en otro idioma tiene millones de vistas. Cobra $9,000.',money:9000},
  {title:'Roaming interplanetario',text:'Olvidaste apagar los datos y tu teléfono intentó conectarse hasta con satélites. Paga $4,000.',money:-4000},
  {title:'Karaoke diplomático',text:'Cantaste tan fuerte que cada jugador aporta $2,000 para que prometas una segunda canción.',collectEach:2000},
  {title:'El café más caro del mundo',text:'Pediste “lo de siempre” sin mirar el menú. Paga $3,000 y disfruta cada sorbo.',money:-3000},
  {title:'Trabajo remoto desde la playa',text:'La videollamada salió perfecta, salvo por el loro que respondió por ti. Cobra $7,500.',money:7500},
  {title:'Broma en el chat grupal',text:'Cambiaste la foto del grupo por una muy comprometedora. Paga $1,500 a cada jugador.',payEach:1500},
  {title:'Concurso de maletas',text:'Tu equipaje ganó por ser el más extraño y colorido. Cobra $6,500.',money:6500},
  {title:'Tren equivocado, gran historia',text:'Llegaste a una ciudad distinta, pero vendiste la historia a una revista. Cobra $5,500.',money:5500},
  {title:'Factura compartida',text:'Elige a un jugador para que te pague $3,000 de aquella reservación grupal.',choosePlayer:{amount:3000}},
  {title:'Inspección sorpresa',text:'Paga $2,500 por cada casa y $8,000 por cada hotel de tu colección.',buildingFee:{house:-2500,hotel:-8000}}
  ,{title:'Ruta panorámica',text:'Avanza 5 casillas y resuelve el nuevo destino.',moveSteps:5}
  ,{title:'Equipaje en la terminal equivocada',text:'Retrocede 4 casillas para recuperarlo.',moveSteps:-4}
  ,{title:'Festival en México',text:'Viaja directamente a México. Cobra Salida si corresponde.',moveTo:14}
  ,{title:'Cadena de favores',text:'Elige a un jugador para recibir $4,000.',choosePlayer:{amount:4000}}
  ,{title:'Regalos para todos',text:'Paga $1,000 a cada jugador; al menos las fotografías quedaron increíbles.',payEach:1000}
]};
function shuffledDeck(type){return [...CARD_DECKS[type]].sort(()=>Math.random()-.5)}

function cleanName(value) { return String(value || '').trim().slice(0, 18); }
function code() { let c; do c = Math.random().toString(36).slice(2,7).toUpperCase(); while (rooms.has(c)); return c; }
function publicRoom(r) { return { ...r,players:r.players.map(({reconnectToken,connectionId,lastChatAt,...player})=>player),board:BOARD,activeDebt:r.debts?.[0]||null,decks:undefined,offers:undefined,debts:undefined,timeout:undefined }; }
function emitOffers(r){r.players.forEach(player=>io.to(player.id).emit('offers',(r.offers||[]).filter(o=>o.buyerId===player.id||o.sellerId===player.id)));}
function emit(r) {r.lastSavedAt=Date.now();persistRooms();io.to(r.code).emit('state', publicRoom(r));emitOffers(r); }
function log(r, message) { r.log.unshift(message); r.log = r.log.slice(0, 20); }
function notify(r,title,text,type='info',target){io.to(target||r.code).emit('gameToast',{title,text,type,id:Date.now()+Math.random()});}
function current(r) { return r.players[r.turn]; }
function roomSettings(r){r.settings={turnDuration:0,disconnectGrace:30,initialMoney:150000,rules:{},...(r.settings||{})};r.settings.turnDuration=0;r.settings.rules={salaryOnStart:true,doubleRentFullGroup:true,extraTurnOnDoubles:true,tripleDoublesJail:true,allowExpropriation:true,allowPropertySwap:true,...(r.settings.rules||{})};return r.settings}
function startTurnClock(r,remaining){const seconds=roomSettings(r).turnDuration;r.turnPaused=false;r.pauseReason=null;r.hostCanSkipAt=null;r.pausedRemaining=null;r.turnDeadline=seconds?Date.now()+(remaining??seconds*1000):null}
function pauseTurnForDisconnect(r){if(r.status!=='playing'||!current(r)||current(r).connected!==false)return;r.pausedRemaining=r.turnDeadline?Math.max(5000,r.turnDeadline-Date.now()):null;r.turnDeadline=null;r.turnPaused=true;r.pauseReason='disconnect';r.hostCanSkipAt=Date.now()+roomSettings(r).disconnectGrace*1000}
function resumeTurnAfterReconnect(r,p){if(r.status==='playing'&&current(r)?.id===p.id&&r.turnPaused&&r.pauseReason==='disconnect')startTurnClock(r,r.pausedRemaining||undefined)}
function defaultStats(){return{rentCollected:0,rentPaid:0,spacesTraveled:0,laps:0,rolls:0,doubles:0,peakDebt:0,propertiesBought:0,housesBuilt:0,hotelsBuilt:0,cardsDrawn:0}}
function statsOf(player){player.stats={...defaultStats(),...(player.stats||{})};return player.stats}
function buildFinalResults(r){const results=r.players.map(player=>{const positions=Object.entries(r.owners).filter(([,owner])=>owner===player.id).map(([position])=>Number(position)),propertyValue=positions.reduce((sum,position)=>sum+(BOARD[position].price||0),0),constructionValue=positions.reduce((sum,position)=>{const tile=BOARD[position],development=r.buildings[position];if(!development)return sum;return sum+(development.hotel?(tile.houseCost*4+tile.hotelCost):(development.houses||0)*tile.houseCost)},0),debt=(r.debts||[]).filter(item=>item.debtorId===player.id).reduce((sum,item)=>sum+item.amount,0),netWorth=player.money+propertyValue+constructionValue-debt;return{id:player.id,name:player.name,color:player.color,token:player.token,bankrupt:player.bankrupt,cash:player.money,propertyValue,constructionValue,debt,netWorth,properties:positions.length,stats:{...statsOf(player)}}}).sort((a,b)=>b.netWorth-a.netWorth);results.forEach((result,index)=>result.rank=index+1);r.finalResults=results;return results}
function nextTurn(r) {
  if (r.players.filter(p => !p.bankrupt).length <= 1) {
    r.status = 'finished';
    const champion=r.players.find(p => !p.bankrupt);r.winner=champion?.name;r.winnerId=champion?.id;buildFinalResults(r);
    log(r, `${r.winner || 'Nadie'} gana la partida.`);
    r.turnDeadline=null;r.turnPaused=false;
    return;
  }
  if(r.extraTurn){r.extraTurn=false;r.phase='notice';r.resumePhase='roll';r.dice=null;r.pending=null;r.gameNotice={type:'double',title:'¡DOBLES! Tienes otro turno',text:`${current(r).name} vuelve a lanzar los dados por haber obtenido dobles.`};startTurnClock(r);log(r,`${current(r).name} vuelve a tirar por obtener dobles.`);return;}
  do r.turn = (r.turn + 1) % r.players.length; while (r.players[r.turn].bankrupt);
  while(current(r).skipTurns>0){current(r).skipTurns--;log(r,`${current(r).name} pierde este turno.`);notify(r,'Turno perdido',`${current(r).name} pierde este turno por el efecto de una carta.`,'warning');do r.turn=(r.turn+1)%r.players.length;while(r.players[r.turn].bankrupt);}
  r.doubles=0;
  r.phase = 'roll';r.resumePhase=null;r.gameNotice=null;r.dice=null;r.pending=null;r.specialEvent=null;r.moveMode=null;
  startTurnClock(r);
  notify(r,'Es tu turno','Lanza los dados cuando estés listo.','turn',current(r).id);
}
function charge(r,player,amount,recipient,reason='Pago pendiente'){
  amount=Math.max(0,Math.floor(amount));if(player.money>=amount){player.money-=amount;if(recipient)recipient.money+=amount;return true;}
  r.debts.push({id:Math.random().toString(36).slice(2,10),debtorId:player.id,creditorId:recipient?.id||null,creditorName:recipient?.name||'Banco',amount,reason});
  statsOf(player).peakDebt=Math.max(statsOf(player).peakDebt,amount);
  log(r,`${player.name} debe reunir $${amount.toLocaleString('es-MX')} para cubrir: ${reason}.`);notify(r,'Pago pendiente',`${player.name} no tiene efectivo suficiente y debe conseguir $${amount.toLocaleString('es-MX')}.`,'danger');return false;
}
function land(r, p, total) {
  const tile = BOARD[p.position];
  if (tile.type === 'goJail') { p.position=10;p.jailed=3;r.extraTurn=false;r.moveMode='deport';r.specialEvent={type:'deported',title:'Pase a Deportado',text:'Tu conducta como turista te envía directamente a Deportado. No recibes sueldo.'};r.phase='special';return log(r, `${p.name} fue enviado a Deportado.`); }
  if (tile.type === 'jail') {r.specialEvent={type:'visit',title:'Visita a Deportado',text:'Estás solamente de visita. No recibes ningún castigo y terminarás tu turno normalmente.'};r.phase='special';return;}
  if (tile.type === 'rest') {r.specialEvent={type:'australia',title:'Un día en Australia',text:'Disfruta los canguros y el paisaje. Aquí no pagas ni recibes dinero. ¿Quieres retar al canguro a muerte?',challenge:true};r.phase='special';return;}
  if (tile.type === 'tax') { charge(r,p,tile.amount); r.phase='end'; return log(r, `${p.name} pagó $${tile.amount}.`); }
  if (tile.type === 'email' || tile.type === 'fax') {
    r.pending={deck:tile.type};r.phase='draw';return log(r,`${p.name} debe tomar una carta de ${tile.type==='fax'?'Correo':'Mensaje'}.`);
  }
  if (['property','transport','diplomatic'].includes(tile.type)) {
    const ownerId=r.owners[p.position];
    if (!ownerId) { r.pending={position:p.position}; r.phase='decision'; return; }
    if (ownerId !== p.id) {
      const owner=r.players.find(x=>x.id===ownerId); let rent=tile.rent;
      if(r.mortgages[p.position]){r.phase='end';log(r,`${tile.name} está hipotecada y no cobra renta.`);notify(r,'Propiedad hipotecada',`${p.name} no paga renta en ${tile.name}.`,'info');return;}
      if(tile.type==='transport'){const count=Object.entries(r.owners).filter(([pos,id])=>id===ownerId&&BOARD[pos].type==='transport').length;rent=[0,2500,5000,10000,20000][count];}
      if(tile.type==='diplomatic'){const count=Object.entries(r.owners).filter(([pos,id])=>id===ownerId&&BOARD[pos].type==='diplomatic').length;rent=total*(count===2?1000:500);}
      if(tile.type==='property'){const development=r.buildings[p.position]||{houses:0,hotel:false};rent=tile.rents[development.hotel?5:development.houses];const block=BOARD.map((x,i)=>({...x,i})).filter(x=>x.group===tile.group);if(roomSettings(r).rules.doubleRentFullGroup&&!development.hotel&&!development.houses&&block.every(x=>r.owners[x.i]===ownerId)){rent*=2;notify(r,'Bloque completo',`${owner.name} posee todo el bloque de ${tile.name}; la renta se duplica.`,'rent');}}
      if(owner.rentBoost){rent*=2;owner.rentBoost=false;notify(r,'Temporada alta',`${owner.name} usa su carta y duplica esta renta.`,'rent');}
      if(!charge(r,p,rent,owner,`Renta de ${tile.name}`)){r.debtResumePhase='end';r.phase='debt';return;}statsOf(owner).rentCollected+=rent;statsOf(p).rentPaid+=rent;log(r, `${p.name} pagó $${rent} a ${owner.name}.`);
      notify(r,'Pago de renta',`${p.name} paga $${rent.toLocaleString('es-MX')} a ${owner.name} por ${tile.name}.`,'rent');
      if(tile.type==='diplomatic'){r.specialEvent={type:'diplomatic',title:tile.name,text:`${owner.name} es propietario. La tirada fue ${total} y la renta es $${rent.toLocaleString('es-MX')}.`};r.phase='special';return;}
    }
  }
  r.phase='end';
}
function drawFromDeck(r,type,p){
  statsOf(p).cardsDrawn++;
  if(!r.decks[type]?.length)r.decks[type]=shuffledDeck(type);const card=r.decks[type].shift();let resolvedText=card.text;r.cardChoice=null;
  if(!card.keep)r.decks[type].push(card);if(card.keep)p.cards.push({type:card.keep,title:card.title});
  if(card.start){r.deferredCardEffect={type:'moveTo',position:0};}else if(card.goJail){r.deferredCardEffect='goJail';}else if(card.money<0)charge(r,p,-card.money,null,card.title);else if(card.money)p.money+=card.money;
  if(card.moveTo!==undefined)r.deferredCardEffect={type:'moveTo',position:card.moveTo};else if(card.moveSteps)r.deferredCardEffect={type:'moveSteps',steps:card.moveSteps};
  if(card.buildingFee){const owned=Object.entries(r.buildings).filter(([position])=>r.owners[position]===p.id),houses=owned.reduce((sum,[,development])=>sum+(development.houses||0),0),hotels=owned.filter(([,development])=>development.hotel).length,amount=houses*Math.abs(card.buildingFee.house)+hotels*Math.abs(card.buildingFee.hotel),insuranceIndex=p.cards.findIndex(saved=>saved.type==='repairInsurance');if(card.buildingFee.house<0&&amount&&insuranceIndex>=0){p.cards.splice(insuranceIndex,1);resolvedText+=` Tu Seguro de mantenimiento cubrió los ${houses} casa(s) y ${hotels} hotel(es): no pagas $${amount.toLocaleString('es-MX')}.`;}else{if(amount){if(card.buildingFee.house<0)charge(r,p,amount,null,card.title);else p.money+=amount;}resolvedText+=` Resultado: ${houses} casa(s), ${hotels} hotel(es), ${card.buildingFee.house<0?'pagas':'recibes'} $${amount.toLocaleString('es-MX')}.`;}}
  if(card.choosePlayer){if(r.players.some(player=>player.id!==p.id&&!player.bankrupt))r.cardChoice={type:'player',playerId:p.id,amount:card.choosePlayer.amount,title:card.title};else resolvedText+=' No quedan otros jugadores disponibles.';}
  if(card.payEach)r.players.filter(x=>x.id!==p.id&&!x.bankrupt).forEach(other=>charge(r,p,card.payEach,other,card.title));
  if(card.collectEach)r.players.filter(x=>x.id!==p.id&&!x.bankrupt).forEach(other=>charge(r,other,card.collectEach,p,card.title));
  if(card.loseTurn)p.skipTurns++;
  r.drawnCard={deck:type,title:card.title,text:resolvedText,player:p.name,kept:Boolean(card.keep),requiresChoice:Boolean(r.cardChoice)};r.card=resolvedText;r.pending=null;r.phase='card';log(r,`${p.name} tomó «${card.title}».`);
}
function blockPositions(group){return BOARD.map((tile,position)=>({tile,position})).filter(x=>x.tile.group===group).map(x=>x.position)}
function developmentLevel(r,position){const d=r.buildings[position];return d?.hotel?5:d?.houses||0}
function expropriationOptions(r,p){const groups=[...new Set(BOARD.filter(tile=>tile.type==='property').map(tile=>tile.group))],options=[];groups.forEach(group=>{const block=blockPositions(group),missing=block.filter(position=>r.owners[position]!==p.id);if(missing.length!==1||block.some(position=>developmentLevel(r,position)>0))return;const position=missing[0],tile=BOARD[position],owner=r.players.find(player=>player.id===r.owners[position]);if(r.mortgages[position])return;options.push({position,name:tile.name,group,ownerName:owner?.name||'Banco',cost:owner?tile.rents[0]:Math.max(0,tile.price-1000)})});return options}
function swappableProperties(r,p,own){return Object.entries(r.owners).filter(([position,owner])=>(own?owner===p.id:owner!==p.id)&&!r.mortgages[position]&&!developmentLevel(r,position)&&BOARD[position]?.price).map(([position,owner])=>({position:Number(position),name:BOARD[position].name,group:BOARD[position].group||BOARD[position].type,ownerName:r.players.find(player=>player.id===owner)?.name||'Jugador'}))}
function applyDeferredCard(r,p){const effect=r.deferredCardEffect;r.deferredCardEffect=null;if(!effect)return false;if(effect==='goJail'||effect.type==='goJail'){p.position=10;p.jailed=3;r.extraTurn=false;r.moveMode='deport';r.specialEvent={type:'deported',title:'Mensaje de las autoridades',text:'La carta te envía directamente a Deportado. No recibes sueldo.'};r.phase='special';return true}const old=p.position,steps=effect.type==='moveTo'?(effect.position-old+40)%40:effect.steps,target=effect.type==='moveTo'?effect.position:(old+steps+400)%40;if(steps>0&&target<old){statsOf(p).laps++;if(roomSettings(r).rules.salaryOnStart){p.money+=20000;log(r,`${p.name} pasó por Salida durante el efecto de una carta y cobró $20,000.`)}}p.position=target;statsOf(p).spacesTraveled+=Math.abs(steps);r.moveMode='card';r.cardMoveSteps=steps;land(r,p,Math.max(1,Math.abs(steps)));return true}
function reconnectKey(){return crypto.randomBytes(24).toString('hex')}
function attachPlayer(socket,r,p){socket.join(r.code);socket.data.room=r.code;p.connectionId=socket.id;p.connected=true;p.disconnectedAt=null;socket.emit('session',{code:r.code,token:p.reconnectToken});}
function migratePlayerId(r,oldId,newId){if(oldId===newId)return;r.owners=Object.fromEntries(Object.entries(r.owners).map(([position,owner])=>[position,owner===oldId?newId:owner]));if(r.host===oldId)r.host=newId;if(r.winnerId===oldId)r.winnerId=newId;r.finalResults?.forEach(result=>{if(result.id===oldId)result.id=newId});r.debts.forEach(debt=>{if(debt.debtorId===oldId)debt.debtorId=newId;if(debt.creditorId===oldId)debt.creditorId=newId});r.offers.forEach(offer=>{if(offer.buyerId===oldId)offer.buyerId=newId;if(offer.sellerId===oldId)offer.sellerId=newId});r.chatMessages.forEach(message=>{if(message.playerId===oldId)message.playerId=newId});if(r.cardChoice?.playerId===oldId)r.cardChoice.playerId=newId;if(r.specialChoice?.playerId===oldId)r.specialChoice.playerId=newId}
function forceSkipTurn(r,reason='Tiempo agotado'){const p=current(r);if(!p||r.phase==='debt')return false;if(r.cardChoice?.type==='player'){const target=r.players.find(player=>player.id!==p.id&&!player.bankrupt);if(target)charge(r,target,r.cardChoice.amount,p,r.cardChoice.title)}if(r.deferredCardEffect==='goJail'){p.position=10;p.jailed=3;r.deferredCardEffect=null}r.cardChoice=null;r.specialChoice=null;r.drawnCard=null;r.specialEvent=null;r.gameNotice=null;r.pending=null;r.extraTurn=false;if(r.debts.length){r.phase='debt';r.debtResumePhase='end';r.turnDeadline=null;log(r,`El reloj de ${p.name} terminó, pero debe resolver una deuda antes de continuar.`);return true}r.phase='end';log(r,`${reason}: se omitió el turno de ${p.name}.`);notify(r,'Turno omitido',`${p.name} perdió el turno: ${reason.toLowerCase()}.`,'warning');nextTurn(r);return true}
function expelPlayer(r,p){if(r.status==='lobby'){r.players=r.players.filter(player=>player.id!==p.id);log(r,`${p.name} fue retirado de la sala.`);return}Object.keys(r.owners).forEach(position=>{if(r.owners[position]!==p.id)return;delete r.owners[position];delete r.mortgages[position];delete r.buildings[position]});r.offers=r.offers.filter(offer=>offer.buyerId!==p.id&&offer.sellerId!==p.id);r.debts=r.debts.filter(debt=>debt.debtorId!==p.id&&debt.creditorId!==p.id);p.money=0;p.bankrupt=true;p.abandoned=true;p.connected=false;log(r,`${p.name} fue retirado de la partida; sus propiedades volvieron al banco.`);notify(r,'Jugador retirado',`${p.name} abandonó definitivamente y sus propiedades regresaron al banco.`,'danger');if(current(r)?.id===p.id||r.players.filter(player=>!player.bankrupt).length<=1)nextTurn(r)}
function restartRoom(r){const initial=roomSettings(r).initialMoney;r.players=r.players.filter(player=>!player.abandoned);r.players.forEach(player=>Object.assign(player,{money:initial,position:0,jailed:0,bankrupt:false,cards:[],skipTurns:0,rentBoost:false,stats:defaultStats()}));Object.assign(r,{status:'lobby',turn:0,phase:'roll',resumePhase:null,debtResumePhase:null,gameNotice:null,dice:null,pending:null,owners:{},mortgages:{},buildings:{},debts:[],offers:[],winner:null,winnerId:null,finalResults:null,card:null,drawnCard:null,cardChoice:null,specialChoice:null,deferredCardEffect:null,specialEvent:null,moveMode:null,cardMoveSteps:null,decks:{fax:shuffledDeck('fax'),email:shuffledDeck('email')},doubles:0,extraTurn:false,manualPaused:false,turnPaused:false,pauseReason:null,turnDeadline:null});r.log=[`La partida fue reiniciada con $${initial.toLocaleString('es-MX')} por jugador.`]}

restoreRooms();
setInterval(()=>{for(const r of rooms.values()){if(r.status!=='playing'||r.turnPaused||!r.turnDeadline||Date.now()<r.turnDeadline)continue;if(r.phase==='debt'){r.turnDeadline+=1000;continue}if(forceSkipTurn(r))emit(r)}},1000).unref();
io.on('connection', socket => {
  socket.use(([event],next)=>{const r=rooms.get(socket.data.room),allowed=['sendChat','toggleRoomPause','restartRoom','deleteRoom','finishRoom','kickPlayer','hostSkipCurrentTurn','setOptionalRule','setInitialMoney'];if(r?.manualPaused&&!allowed.includes(event)){socket.emit('errorMessage','La partida está pausada por el anfitrión.');return}next()});
  socket.on('create', ({name}) => {
    name=cleanName(name); if(!name) return socket.emit('errorMessage','Escribe tu nombre.');
    const c=code(); const player={id:socket.id,name,color:COLORS[0],token:TOKENS[0],money:150000,position:0,jailed:0,bankrupt:false,connected:true,reconnectToken:reconnectKey(),connectionId:socket.id,cards:[],skipTurns:0,stats:defaultStats()};
    const room={code:c,host:socket.id,status:'lobby',players:[player],turn:0,phase:'roll',resumePhase:null,debtResumePhase:null,gameNotice:null,dice:null,pending:null,owners:{},mortgages:{},buildings:{},debts:[],offers:[],chatMessages:[],log:[`${name} creó la sala.`],winner:null,card:null,drawnCard:null,deferredCardEffect:null,specialEvent:null,moveMode:null,decks:{fax:shuffledDeck('fax'),email:shuffledDeck('email')},doubles:0,extraTurn:false,settings:{turnDuration:0,disconnectGrace:30,initialMoney:150000,rules:{}},turnDeadline:null,turnPaused:false,manualPaused:false};roomSettings(room);
    rooms.set(c,room);attachPlayer(socket,room,player);emit(room);
  });
  socket.on('join', ({name,code:raw,reconnectToken}) => {
    const c=String(raw||'').toUpperCase(),r=rooms.get(c);name=cleanName(name);
    if(!r)return socket.emit('errorMessage','La sala no existe.');
    const returning=reconnectToken&&r.players.find(player=>player.reconnectToken===reconnectToken&&!player.bankrupt);
    if(returning){const oldId=returning.id,oldSocket=io.sockets.sockets.get(returning.connectionId);migratePlayerId(r,oldId,socket.id);returning.id=socket.id;if(oldSocket&&oldSocket.id!==socket.id)oldSocket.disconnect(true);attachPlayer(socket,r,returning);resumeTurnAfterReconnect(r,returning);log(r,`${returning.name} se reconectó.`);notify(r,'Jugador reconectado',`${returning.name} volvió a la partida.`,'success');emit(r);return;}
    if(r.status!=='lobby')return socket.emit('errorMessage','La partida ya empezó y no admite jugadores nuevos.');
    if(!name||r.players.length>=6)return socket.emit('errorMessage','Nombre inválido o sala llena.');
    const player={id:socket.id,name,color:COLORS[r.players.length],token:TOKENS[r.players.length],money:roomSettings(r).initialMoney,position:0,jailed:0,bankrupt:false,connected:true,reconnectToken:reconnectKey(),connectionId:socket.id,cards:[],skipTurns:0,stats:defaultStats()};r.players.push(player);
    attachPlayer(socket,r,player);log(r,`${name} se unió.`);emit(r);
  });
  socket.on('selectToken', (token, acknowledge) => {
    const r=rooms.get(socket.data.room);
    if(!r||r.status!=='lobby'||!TOKENS.includes(token)||r.players.some(p=>p.id!==socket.id&&p.token===token)){if(typeof acknowledge==='function')acknowledge(false);return;}
    const p=r.players.find(p=>p.id===socket.id); if(p){p.token=token;emit(r);if(typeof acknowledge==='function')acknowledge(true);}
  });
  socket.on('start', () => { const r=rooms.get(socket.data.room); if(!r||r.host!==socket.id||r.players.length<2)return; r.status='playing';startTurnClock(r);log(r,'Comienza la vuelta al mundo.'); emit(r); });
  socket.on('drawCard', type => {const r=rooms.get(socket.data.room);if(!r||current(r)?.id!==socket.id||r.phase!=='draw'||r.pending?.deck!==type)return;drawFromDeck(r,type,current(r));emit(r);});
  socket.on('resolveCard', () => {const r=rooms.get(socket.data.room);if(!r||current(r)?.id!==socket.id||r.phase!=='card'||r.cardChoice)return;const p=current(r);r.drawnCard=null;if(applyDeferredCard(r,p)){}else if(r.debts.length){r.debtResumePhase='end';r.phase='debt';}else r.phase='end';emit(r);});
  socket.on('chooseCardPlayer',targetId=>{const r=rooms.get(socket.data.room),choice=r?.cardChoice,p=r&&current(r),target=r?.players.find(player=>player.id===targetId&&!player.bankrupt);if(!r||r.phase!=='card'||p?.id!==socket.id||choice?.type!=='player'||choice.playerId!==p.id||!target||target.id===p.id)return;charge(r,target,choice.amount,p,choice.title);log(r,`${p.name} eligió a ${target.name} para «${choice.title}».`);r.cardChoice=null;emit(r);});
  socket.on('resolveAustraliaChallenge', accept => {const r=rooms.get(socket.data.room),p=r&&current(r);if(!r||p?.id!==socket.id||r.phase!=='special'||r.specialEvent?.type!=='australia'||!r.specialEvent.challenge)return;if(!accept){log(r,`${p.name} decidió no retar al canguro.`);r.specialEvent=null;r.phase='end';return emit(r)}const won=Math.random()<.5;if(won){p.money+=5000;r.specialEvent={type:'australia',title:'¡Venciste al canguro!',text:'Tras un duelo legendario de miradas y saltos, el canguro acepta la derrota. Ganas $5,000.',resolved:true};log(r,`${p.name} venció al canguro de Australia y ganó $5,000.`);notify(r,'¡Victoria australiana!',`${p.name} gana $5,000 tras vencer al canguro.`,'success')}else{charge(r,p,5000,null,'Derrota contra el canguro');r.specialEvent={type:'australia',title:'El canguro fue más fuerte',text:'Calculaste mal el salto y el campeón australiano te mandó directo al suelo. Pierdes $5,000.',resolved:true};log(r,`${p.name} perdió contra el canguro de Australia y debe pagar $5,000.`);notify(r,'Derrota australiana',`${p.name} pierde $5,000 contra el canguro.`,'danger')}emit(r)});
  socket.on('resolveSpecial', () => {const r=rooms.get(socket.data.room);if(!r||current(r)?.id!==socket.id||r.phase!=='special')return;r.specialEvent=null;if(r.debts.length){r.debtResumePhase='end';r.phase='debt'}else r.phase='end';emit(r);});
  socket.on('resolveNotice', () => {const r=rooms.get(socket.data.room);if(!r||current(r)?.id!==socket.id||r.phase!=='notice')return;r.phase=r.resumePhase||'roll';r.resumePhase=null;r.gameNotice=null;emit(r);});
  socket.on('payBail', () => {const r=rooms.get(socket.data.room),p=r&&current(r);if(!r||p?.id!==socket.id||r.phase!=='roll'||!p.jailed||p.money<5000)return;charge(r,p,5000);p.jailed=0;log(r,`${p.name} pagó $5,000 y recuperó su pasaporte.`);notify(r,'Multa pagada',`${p.name} paga $5,000 y ya puede lanzar los dados.`,'money');emit(r);});
  socket.on('usePassport', () => {const r=rooms.get(socket.data.room),p=r&&current(r);if(!r||p?.id!==socket.id||r.phase!=='roll'||!p.jailed)return;const index=p.cards.findIndex(card=>card.type==='passport');if(index<0)return;p.cards.splice(index,1);p.jailed=0;log(r,`${p.name} usó su carta para salir de Deportado.`);notify(r,'Pasaporte utilizado',`${p.name} usa su carta y sale de Deportado sin pagar multa.`,'success');emit(r);});
  socket.on('useRentBoost',()=>{const r=rooms.get(socket.data.room),p=r&&current(r);if(!r||p?.id!==socket.id||!['roll','end'].includes(r.phase)||p.rentBoost)return;const index=p.cards.findIndex(card=>card.type==='rentBoost');if(index<0)return;p.cards.splice(index,1);p.rentBoost=true;log(r,`${p.name} activó Temporada alta: su próxima renta será doble.`);notify(r,'Temporada alta activada',`La siguiente renta que cobre ${p.name} será doble.`,'success');emit(r);});
  socket.on('usePropertySwap',()=>{const r=rooms.get(socket.data.room),p=r&&current(r);if(!r||!roomSettings(r).rules.allowPropertySwap||p?.id!==socket.id||!['roll','end'].includes(r.phase)||!p.cards.some(card=>card.type==='propertySwap'))return socket.emit('errorMessage','El intercambio de propiedades está desactivado.');const ownOptions=swappableProperties(r,p,true),targetOptions=swappableProperties(r,p,false);if(!ownOptions.length||!targetOptions.length)return socket.emit('errorMessage','No hay propiedades libres de hipotecas y construcciones para intercambiar.');r.specialChoice={type:'propertySwap',playerId:p.id,resumePhase:r.phase,ownOptions,targetOptions};r.phase='specialChoice';emit(r);});
  socket.on('resolvePropertySwap',({ownPosition,targetPosition})=>{const r=rooms.get(socket.data.room),choice=r?.specialChoice,p=r&&current(r);ownPosition=Number(ownPosition);targetPosition=Number(targetPosition);if(!r||p?.id!==socket.id||choice?.type!=='propertySwap'||choice.playerId!==p.id)return;const own=swappableProperties(r,p,true).find(option=>option.position===ownPosition),target=swappableProperties(r,p,false).find(option=>option.position===targetPosition),cardIndex=p.cards.findIndex(card=>card.type==='propertySwap');if(!own||!target||cardIndex<0)return socket.emit('errorMessage','El intercambio ya no es válido.');const otherId=r.owners[targetPosition];r.owners[ownPosition]=otherId;r.owners[targetPosition]=p.id;r.offers=r.offers.filter(offer=>![ownPosition,targetPosition].includes(offer.position));p.cards.splice(cardIndex,1);r.phase=choice.resumePhase||'end';r.specialChoice=null;log(r,`${p.name} intercambió ${BOARD[ownPosition].name} por ${BOARD[targetPosition].name} con ${target.ownerName}.`);notify(r,'Intercambio cultural',`${p.name} recibe ${BOARD[targetPosition].name} y entrega ${BOARD[ownPosition].name}.`,'success');emit(r);});
  socket.on('useExpropriation',()=>{const r=rooms.get(socket.data.room),p=r&&current(r);if(!r||!roomSettings(r).rules.allowExpropriation||p?.id!==socket.id||!['roll','end'].includes(r.phase)||p.jailed||!p.cards.some(card=>card.type==='expropriation'))return socket.emit('errorMessage','La Expropiación no está disponible con las reglas actuales.');const options=expropriationOptions(r,p);if(!options.length)return socket.emit('errorMessage','No tienes un bloque al que le falte exactamente una propiedad disponible.');r.specialChoice={type:'expropriation',playerId:p.id,resumePhase:r.phase,options};r.phase='specialChoice';emit(r);});
  socket.on('cancelSpecialChoice',()=>{const r=rooms.get(socket.data.room),choice=r?.specialChoice;if(!r||choice?.playerId!==socket.id)return;r.phase=choice.resumePhase||'end';r.specialChoice=null;emit(r);});
  socket.on('resolveExpropriation',rawPosition=>{const r=rooms.get(socket.data.room),choice=r?.specialChoice,p=r&&current(r),position=Number(rawPosition);if(!r||p?.id!==socket.id||choice?.type!=='expropriation'||choice.playerId!==p.id)return;const valid=expropriationOptions(r,p).find(option=>option.position===position),cardIndex=p.cards.findIndex(card=>card.type==='expropriation');if(!valid||cardIndex<0)return socket.emit('errorMessage','Esa propiedad ya no está disponible para expropiación.');if(p.money<valid.cost)return socket.emit('errorMessage','No tienes efectivo suficiente para completar esta compra especial.');const owner=r.players.find(player=>player.id===r.owners[position]);p.money-=valid.cost;if(owner)owner.money+=valid.cost;r.owners[position]=p.id;r.offers=r.offers.filter(offer=>offer.position!==position);p.cards.splice(cardIndex,1);statsOf(p).propertiesBought++;r.phase=choice.resumePhase||'end';r.specialChoice=null;log(r,`${p.name} usó Expropiación para adquirir ${BOARD[position].name} por $${valid.cost.toLocaleString('es-MX')} y completar el grupo.`);notify(r,'¡Grupo completado!',`${p.name} adquiere ${BOARD[position].name} mediante Expropiación.`,'success');emit(r);});
  socket.on('mortgageProperty', position => {const r=rooms.get(socket.data.room),p=r?.players.find(x=>x.id===socket.id);position=Number(position);const tile=BOARD[position];if(!r||r.status!=='playing'||!p||p.bankrupt||r.owners[position]!==p.id||r.mortgages[position]||!tile?.price)return;if(tile.group&&blockPositions(tile.group).some(pos=>developmentLevel(r,pos)>0))return socket.emit('errorMessage','Primero vende todas las construcciones de este bloque.');const value=Math.floor(tile.price/2);r.mortgages[position]=true;p.money+=value;log(r,`${p.name} hipotecó ${tile.name} por $${value.toLocaleString('es-MX')}.`);notify(r,'Propiedad hipotecada',`${p.name} recibe $${value.toLocaleString('es-MX')} por ${tile.name}.`,'money');emit(r);});
  socket.on('unmortgageProperty', position => {const r=rooms.get(socket.data.room),p=r?.players.find(x=>x.id===socket.id);position=Number(position);const tile=BOARD[position],cost=tile?Math.ceil(tile.price*.55):0;if(!r||r.status!=='playing'||!p||p.bankrupt||r.owners[position]!==p.id||!r.mortgages[position]||p.money<cost)return;p.money-=cost;delete r.mortgages[position];log(r,`${p.name} recuperó ${tile.name} pagando $${cost.toLocaleString('es-MX')}.`);notify(r,'Hipoteca liquidada',`${tile.name} vuelve a producir renta.`,'success');emit(r);});
  socket.on('buyHouse',position=>{const r=rooms.get(socket.data.room),p=r?.players.find(x=>x.id===socket.id);position=Number(position);const tile=BOARD[position];if(!r||!p||p.bankrupt||tile?.type!=='property'||r.owners[position]!==p.id)return;const block=blockPositions(tile.group),level=developmentLevel(r,position);if(!block.every(pos=>r.owners[pos]===p.id))return socket.emit('errorMessage','Necesitas poseer el bloque completo.');if(block.some(pos=>r.mortgages[pos]))return socket.emit('errorMessage','No puedes construir con una propiedad hipotecada.');if(level>=4||level!==Math.min(...block.map(pos=>developmentLevel(r,pos))))return socket.emit('errorMessage','Debes construir uniformemente en todo el bloque.');if(p.money<tile.houseCost)return socket.emit('errorMessage','No tienes suficiente dinero para construir.');p.money-=tile.houseCost;r.buildings[position]={houses:level+1,hotel:false};statsOf(p).housesBuilt++;log(r,`${p.name} construyó una casa en ${tile.name}.`);notify(r,'Nueva casa',`${tile.name} ahora tiene ${level+1} casa(s).`,'success');emit(r);});
  socket.on('buyHotel',position=>{const r=rooms.get(socket.data.room),p=r?.players.find(x=>x.id===socket.id);position=Number(position);const tile=BOARD[position];if(!r||!p||p.bankrupt||tile?.type!=='property'||r.owners[position]!==p.id)return;const block=blockPositions(tile.group),level=developmentLevel(r,position);if(level!==4||level!==Math.min(...block.map(pos=>developmentLevel(r,pos)))||block.some(pos=>r.mortgages[pos]))return socket.emit('errorMessage','Necesitas cuatro casas uniformes y ninguna hipoteca.');if(p.money<tile.hotelCost)return socket.emit('errorMessage','No tienes suficiente dinero para construir el hotel.');p.money-=tile.hotelCost;r.buildings[position]={houses:0,hotel:true};statsOf(p).hotelsBuilt++;log(r,`${p.name} construyó un hotel en ${tile.name}.`);notify(r,'¡Nuevo hotel!',`${tile.name} alcanza su máximo desarrollo.`,'success');emit(r);});
  socket.on('sellBuilding',position=>{const r=rooms.get(socket.data.room),p=r?.players.find(x=>x.id===socket.id);position=Number(position);const tile=BOARD[position],d=r?.buildings[position];if(!r||!p||p.bankrupt||tile?.type!=='property'||r.owners[position]!==p.id||!d)return;const block=blockPositions(tile.group),level=developmentLevel(r,position);if(level!==Math.max(...block.map(pos=>developmentLevel(r,pos))))return socket.emit('errorMessage','Debes vender construcciones uniformemente.');if(d.hotel){r.buildings[position]={houses:4,hotel:false};p.money+=Math.floor(tile.hotelCost/2);}else if(d.houses){d.houses--;p.money+=Math.floor(tile.houseCost/2);if(!d.houses)delete r.buildings[position];}log(r,`${p.name} vendió una construcción de ${tile.name} al banco.`);emit(r);});
  socket.on('payDebt', () => {const r=rooms.get(socket.data.room),debt=r?.debts?.[0],debtor=r?.players.find(p=>p.id===socket.id);if(!r||!debt||debt.debtorId!==socket.id||!debtor||debtor.money<debt.amount)return;debtor.money-=debt.amount;const creditor=r.players.find(p=>p.id===debt.creditorId);if(creditor)creditor.money+=debt.amount;r.debts.shift();log(r,`${debtor.name} cubrió su deuda de $${debt.amount.toLocaleString('es-MX')}.`);notify(r,'Deuda pagada',`${debtor.name} reunió el dinero y cubrió ${debt.reason}.`,'success');if(!r.debts.length){r.phase=r.debtResumePhase||'end';r.debtResumePhase=null;}emit(r);});
  socket.on('declareBankruptcy', () => {const r=rooms.get(socket.data.room),debt=r?.debts?.[0],debtor=r?.players.find(p=>p.id===socket.id);if(!r||!debt||debt.debtorId!==socket.id||!debtor)return;const creditor=r.players.find(p=>p.id===debt.creditorId);let liquidation=0;Object.keys(r.buildings).forEach(pos=>{if(r.owners[pos]!==debtor.id)return;const d=r.buildings[pos],tile=BOARD[pos];liquidation+=d.hotel?Math.floor(tile.hotelCost/2):d.houses*Math.floor(tile.houseCost/2);delete r.buildings[pos];});debtor.money+=liquidation;if(creditor){creditor.money+=Math.max(0,debtor.money);let interest=0;Object.keys(r.owners).forEach(pos=>{if(r.owners[pos]===debtor.id){r.owners[pos]=creditor.id;if(r.mortgages[pos])interest+=Math.ceil(BOARD[pos].price*.05);}});if(interest)charge(r,creditor,interest,null,'Intereses de propiedades hipotecadas recibidas');}else Object.keys(r.owners).forEach(pos=>{if(r.owners[pos]===debtor.id){delete r.owners[pos];delete r.mortgages[pos];}});debtor.money=0;debtor.bankrupt=true;r.offers=r.offers.filter(o=>o.buyerId!==debtor.id&&o.sellerId!==debtor.id);r.debts=r.debts.filter(d=>d.debtorId!==debtor.id);log(r,`${debtor.name} se declaró en quiebra${liquidation?` y liquidó construcciones por $${liquidation.toLocaleString('es-MX')}`:''}.`);notify(r,'Quiebra declarada',creditor?`${debtor.name} entrega sus bienes a ${creditor.name}.`:`${debtor.name} devuelve sus bienes al banco.`,'danger');if(r.debts.length){r.phase='debt';}else if(current(r)?.id===debtor.id){r.phase='end';nextTurn(r);}else{r.phase=r.debtResumePhase||'end';r.debtResumePhase=null;}emit(r);});
  socket.on('makeOffer', ({sellerId,position,amount}, acknowledge) => {const r=rooms.get(socket.data.room),buyer=r?.players.find(p=>p.id===socket.id),seller=r?.players.find(p=>p.id===sellerId);position=Number(position);amount=Math.floor(Number(amount));const fail=message=>{if(typeof acknowledge==='function')acknowledge({ok:false,message})};if(!r||r.status!=='playing'||!buyer||!seller||buyer.bankrupt||seller.bankrupt||buyer.id===seller.id)return fail('Oferta inválida.');const tile=BOARD[position];if(r.owners[position]!==seller.id||!tile?.price)return fail('La propiedad ya no pertenece a ese jugador.');if(tile.group&&blockPositions(tile.group).some(pos=>developmentLevel(r,pos)>0))return fail('Primero deben venderse todas las construcciones del bloque.');if(!Number.isFinite(amount)||amount<1||amount>buyer.money)return fail('La cantidad no es válida o supera tu efectivo.');if(r.offers.filter(o=>o.buyerId===buyer.id).length>=12)return fail('Tienes demasiadas ofertas pendientes.');const offer={id:Math.random().toString(36).slice(2,10),buyerId:buyer.id,buyerName:buyer.name,sellerId:seller.id,sellerName:seller.name,position,propertyName:tile.name,amount,createdAt:Date.now()};r.offers.push(offer);emitOffers(r);io.to(seller.id).emit('offerNotification',offer);if(typeof acknowledge==='function')acknowledge({ok:true});});
  socket.on('respondOffer',({offerId,accept},acknowledge)=>{const r=rooms.get(socket.data.room),index=r?.offers.findIndex(o=>o.id===offerId);const fail=message=>{if(typeof acknowledge==='function')acknowledge({ok:false,message})};if(!r||index<0)return fail('La oferta ya no está disponible.');const offer=r.offers[index],seller=r.players.find(p=>p.id===socket.id),buyer=r.players.find(p=>p.id===offer.buyerId),tile=BOARD[offer.position];if(!seller||offer.sellerId!==seller.id)return fail('No puedes responder esta oferta.');r.offers.splice(index,1);if(!accept){emitOffers(r);io.to(buyer.id).emit('offerResult',{accepted:false,propertyName:offer.propertyName});if(typeof acknowledge==='function')acknowledge({ok:true});return;}if(tile.group&&blockPositions(tile.group).some(pos=>developmentLevel(r,pos)>0)){emitOffers(r);return fail('Primero deben venderse todas las construcciones del bloque.');}const interest=r.mortgages[offer.position]?Math.ceil(tile.price*.05):0;if(!buyer||buyer.bankrupt||seller.bankrupt||r.owners[offer.position]!==seller.id||buyer.money<offer.amount+interest){emitOffers(r);io.to(buyer?.id||'').emit('offerResult',{accepted:false,propertyName:offer.propertyName,reason:'La operación ya no es válida.'});return fail('La propiedad o el saldo cambiaron.');}buyer.money-=offer.amount+interest;seller.money+=offer.amount;r.owners[offer.position]=buyer.id;r.offers=r.offers.filter(o=>o.position!==offer.position);log(r,`${seller.name} vendió ${offer.propertyName} a ${buyer.name} por $${offer.amount.toLocaleString('es-MX')}${interest?` y el comprador pagó $${interest.toLocaleString('es-MX')} de intereses`:''}.`);io.to(buyer.id).emit('offerResult',{accepted:true,propertyName:offer.propertyName,amount:offer.amount});emit(r);if(typeof acknowledge==='function')acknowledge({ok:true});});
  socket.on('roll', () => {
    const r=rooms.get(socket.data.room); if(!r||r.status!=='playing'||current(r)?.id!==socket.id||r.phase!=='roll')return;
    const p=current(r); const a=1+Math.floor(Math.random()*6), b=1+Math.floor(Math.random()*6),isDouble=a===b,wasJailed=Boolean(p.jailed); r.dice=[a,b]; r.card=null;
    statsOf(p).rolls++;statsOf(p).spacesTraveled+=a+b;if(isDouble)statsOf(p).doubles++;
    if(p.jailed){if(isDouble){p.jailed=0;r.extraTurn=false;log(r,`${p.name} salió de Deportado con dobles.`);notify(r,'¡Pasaporte recuperado!',`${p.name} obtuvo dobles y sale de Deportado.`,'success');}else if(p.jailed>1){p.jailed--;r.phase='end';log(r,`${p.name} sigue Deportado (${p.jailed} intento(s)).`);notify(r,'Sigue Deportado',`${p.name} no obtuvo dobles. Le quedan ${p.jailed} intento(s).`,'warning');return emit(r);}else{charge(r,p,5000);p.jailed=0;r.extraTurn=false;log(r,`${p.name} agotó sus intentos y pagó la multa obligatoria de $5,000.`);notify(r,'Multa obligatoria',`${p.name} agotó sus intentos y paga $5,000 para continuar.`,'warning');if(p.bankrupt){r.phase='end';return emit(r);}}}
    if(roomSettings(r).rules.extraTurnOnDoubles&&!wasJailed&&isDouble){r.doubles++;r.extraTurn=true;if(roomSettings(r).rules.tripleDoublesJail&&r.doubles>=3){p.position=10;p.jailed=3;r.extraTurn=false;r.moveMode='deport';r.specialEvent={type:'deported',title:'Tres dobles consecutivos',text:'Abusaste de las leyes internacionales y fuiste enviado directamente a Deportado.'};r.phase='special';log(r,`${p.name} obtuvo tres dobles y fue Deportado.`);return emit(r);}notify(r,'¡Dados dobles!',`${p.name} obtuvo ${a} y ${b}. Al terminar esta jugada tendrá un turno extra.`,'double');}else if(!wasJailed){r.doubles=0;r.extraTurn=false;}
    const old=p.position; p.position=(old+a+b)%40; if(p.position<old){statsOf(p).laps++;if(roomSettings(r).rules.salaryOnStart){p.money+=20000;log(r,`${p.name} pasó por la salida y cobró $20,000.`);notify(r,'Sueldo de viajero',`${p.name} pasó por Salida y recibe $20,000.`,'money');}}
    log(r,`${p.name} lanzó ${a} + ${b} y llegó a ${BOARD[p.position].name}.`); land(r,p,a+b); emit(r);
  });
  socket.on('buy', () => { const r=rooms.get(socket.data.room); if(!r||current(r)?.id!==socket.id||r.phase!=='decision')return; const p=current(r), pos=r.pending.position,t=BOARD[pos]; if(p.money>=t.price){p.money-=t.price;r.owners[pos]=p.id;statsOf(p).propertiesBought++;log(r,`${p.name} compró ${t.name} por $${t.price}.`);notify(r,'Nueva propiedad',`${p.name} compra ${t.name} por $${t.price.toLocaleString('es-MX')}.`,'money');} r.pending=null;r.phase='end';emit(r); });
  socket.on('skip', () => { const r=rooms.get(socket.data.room); if(!r||current(r)?.id!==socket.id||r.phase!=='decision')return; r.pending=null;r.phase='end';emit(r); });
  socket.on('endTurn', () => { const r=rooms.get(socket.data.room); if(!r||current(r)?.id!==socket.id||r.phase!=='end')return; nextTurn(r);emit(r); });
  socket.on('toggleRoomPause',paused=>{const r=rooms.get(socket.data.room);if(!r||r.host!==socket.id||r.status!=='playing')return;r.manualPaused=Boolean(paused);if(r.manualPaused){r.turnPaused=true;r.pauseReason='host';r.turnDeadline=null;log(r,'El anfitrión pausó la partida.');notify(r,'Partida pausada','Las acciones quedan bloqueadas hasta que el anfitrión reanude.','warning')}else{if(current(r)?.connected===false)pauseTurnForDisconnect(r);else{r.turnPaused=false;r.pauseReason=null;r.hostCanSkipAt=null;startTurnClock(r)}log(r,'El anfitrión reanudó la partida.');notify(r,'Partida reanudada','La vuelta al mundo continúa.','success')}emit(r);});
  socket.on('setInitialMoney',rawAmount=>{const r=rooms.get(socket.data.room),amount=Number(rawAmount);if(!r||r.host!==socket.id||r.status!=='lobby'||![100000,150000,200000,250000].includes(amount))return;roomSettings(r).initialMoney=amount;r.players.forEach(player=>player.money=amount);log(r,`El dinero inicial se configuró en $${amount.toLocaleString('es-MX')}.`);emit(r);});
  socket.on('setOptionalRule',({rule,enabled})=>{const r=rooms.get(socket.data.room),rules=r&&roomSettings(r).rules;if(!r||r.host!==socket.id||r.status!=='lobby'||!Object.prototype.hasOwnProperty.call(rules,rule))return;rules[rule]=Boolean(enabled);log(r,`Regla «${rule}» ${enabled?'activada':'desactivada'}.`);emit(r);});
  socket.on('hostSkipCurrentTurn',()=>{const r=rooms.get(socket.data.room);if(!r||r.host!==socket.id||r.status!=='playing')return;if(!forceSkipTurn(r,'Decisión del anfitrión'))return socket.emit('errorMessage','No se puede saltar mientras existe una deuda obligatoria.');emit(r);});
  socket.on('kickPlayer',playerId=>{const r=rooms.get(socket.data.room),p=r?.players.find(player=>player.id===playerId);if(!r||r.host!==socket.id||!p||p.id===r.host)return;io.to(p.id).emit('playerKicked',{code:r.code});const connection=io.sockets.sockets.get(p.connectionId);expelPlayer(r,p);emit(r);if(connection)connection.disconnect(true);});
  socket.on('restartRoom',()=>{const r=rooms.get(socket.data.room);if(!r||r.host!==socket.id)return;restartRoom(r);notify(r,'Partida reiniciada','Todos vuelven al lobby con el patrimonio restaurado.','success');emit(r);});
  socket.on('skipDisconnectedTurn',playerId=>{const r=rooms.get(socket.data.room),p=r&&current(r);if(!r||r.host!==socket.id||p?.id!==playerId||p.connected||!r.hostCanSkipAt||Date.now()<r.hostCanSkipAt)return socket.emit('errorMessage','Aún no puedes omitir este turno.');if(forceSkipTurn(r,'Jugador desconectado'))emit(r);});
  socket.on('expelDisconnectedPlayer',playerId=>{const r=rooms.get(socket.data.room),p=r?.players.find(player=>player.id===playerId);if(!r||r.host!==socket.id||!p||p.connected||p.bankrupt||!p.disconnectedAt||Date.now()<p.disconnectedAt+roomSettings(r).disconnectGrace*1000)return socket.emit('errorMessage','Ese jugador todavía no puede ser retirado.');expelPlayer(r,p);emit(r);});
  socket.on('finishRoom',()=>{const r=rooms.get(socket.data.room);if(!r||r.host!==socket.id||r.status==='finished')return;r.status='finished';r.phase='end';r.winner=null;r.winnerId=null;r.endedByHost=true;buildFinalResults(r);log(r,'El anfitrión finalizó la partida.');notify(r,'Partida finalizada','El anfitrión cerró la partida. La sala y su historial permanecen guardados.','warning');emit(r);});
  socket.on('deleteRoom',()=>{const r=rooms.get(socket.data.room);if(!r||r.host!==socket.id)return;io.to(r.code).emit('roomDeleted',{code:r.code});rooms.delete(r.code);persistRooms();});
  socket.on('sendChat',(value,acknowledge)=>{const r=rooms.get(socket.data.room),p=r?.players.find(x=>x.id===socket.id),text=String(value||'').trim().replace(/\s+/g,' ').slice(0,180),fail=message=>typeof acknowledge==='function'&&acknowledge({ok:false,message});if(!r||!p||p.bankrupt||!text)return fail('El mensaje está vacío o ya no participas.');if(p.lastChatAt&&Date.now()-p.lastChatAt<700)return fail('Espera un momento antes de enviar otro mensaje.');p.lastChatAt=Date.now();r.chatMessages.push({id:Date.now().toString(36)+socket.id.slice(0,3),playerId:p.id,name:p.name,color:p.color,text,time:Date.now()});r.chatMessages=r.chatMessages.slice(-80);emit(r);if(typeof acknowledge==='function')acknowledge({ok:true});});
  socket.on('disconnect', () => {const r=rooms.get(socket.data.room);if(!r)return;const p=r.players.find(x=>x.id===socket.id&&x.connectionId===socket.id);if(!p)return;p.connected=false;p.disconnectedAt=Date.now();if(current(r)?.id===p.id)pauseTurnForDisconnect(r);if(r.host===p.id){const replacement=r.players.find(player=>player.connected&&!player.bankrupt);if(replacement){r.host=replacement.id;log(r,`${replacement.name} es ahora el anfitrión.`)}}log(r,`${p.name} se desconectó. Puede volver con el mismo enlace.`);notify(r,'Jugador desconectado',`${p.name} perdió la conexión; su lugar está reservado.${current(r)?.id===p.id?' El turno quedó pausado.':''}`,'warning');emit(r);});
});

server.listen(process.env.PORT || 3001, () => console.log(`Juego listo en http://localhost:${process.env.PORT || 3001}`));
