const COLORS=['red','yellow','green','blue'];
const COLOR_NAMES={red:'rojo',yellow:'amarillo',green:'verde',blue:'azul'};
const uid=()=>Math.random().toString(36).slice(2,10);
const shuffle=list=>{const copy=[...list];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
function deck(){const cards=[];for(const color of COLORS){cards.push({id:uid(),color,type:'number',value:0});for(let n=1;n<=9;n++)for(let copy=0;copy<2;copy++)cards.push({id:uid(),color,type:'number',value:n});for(const type of ['draw2','reverse','skip'])for(let copy=0;copy<2;copy++)cards.push({id:uid(),color,type})}for(let i=0;i<4;i++){cards.push({id:uid(),color:null,type:'wild'});cards.push({id:uid(),color:null,type:'wild4'})}return shuffle(cards)}
function label(card){return card.type==='number'?String(card.value):({draw2:'+2',reverse:'Cambio de sentido',skip:'Pierde el turno',wild:'Comodín',wild4:'+4 comodín'}[card.type]||card.type)}
function refill(r){if(r.unoDeck.length)return;r.unoDeck=deck()}
function draw(r,p,count=1){for(let i=0;i<count;i++){refill(r);const card=r.unoDeck.pop();if(card)p.unoHand.push(card)}}
function activePlayers(r){return r.players.filter(p=>!p.abandoned)}
function advance(r,steps=1){const active=activePlayers(r);if(!active.length)return;for(let i=0;i<steps;i++){do r.turn=(r.turn+r.unoDirection+r.players.length)%r.players.length;while(r.players[r.turn].abandoned)}r.unoDrawnCardId=null;r.phase='unoPlay'}
function playable(r,card,p){const top=r.unoDiscard.at(-1),sameNumber=card.type==='number'&&top?.type==='number'&&Number(card.value)===Number(top.value);if(r.unoDrawStack)return card.type==='draw2';if(card.type==='wild')return true;if(card.type==='wild4')return !p.unoHand.some(other=>other.id!==card.id&&other.color===r.unoColor);return card.color===r.unoColor||sameNumber||(card.type!=='number'&&card.type===top.type)}
function clearCatchWindow(r){r.unoVulnerable=null}
function resolvePlay(r,log){const pending=r.unoPendingPlay,p=r.players.find(x=>x.id===pending.playerId),index=p?.unoHand.findIndex(card=>card.id===pending.cardId);if(!p||index<0){r.unoPendingPlay=null;return}const [card]=p.unoHand.splice(index,1);r.unoDiscard.push(card);r.unoColor=card.color||pending.chosenColor;clearCatchWindow(r);log(r,`${p.name} jugó ${label(card)}${card.color?` (${COLOR_NAMES[card.color]})`:` y eligió ${COLOR_NAMES[r.unoColor]}`}.`);r.unoPendingPlay=null;r.unoDrawnCardId=null;if(!p.unoHand.length){p.unoCalled=false;r.status='finished';r.winner=p.name;r.winnerId=p.id;r.phase='end';log(r,`${p.name} se quedó sin cartas y ganó la ronda.`);return}if(p.unoHand.length===1&&!pending.calledUno)r.unoVulnerable=p.id;p.unoCalled=false;if(card.type==='draw2'){r.unoDrawStack=(r.unoDrawStack||0)+2;advance(r);return}if(card.type==='wild4'){advance(r);draw(r,r.players[r.turn],4);log(r,`${r.players[r.turn].name} tomó cuatro cartas y perdió el turno.`);advance(r);return}if(card.type==='reverse'){r.unoDirection*=-1;advance(r,activePlayers(r).length===2?2:1);return}if(card.type==='skip'){advance(r,2);return}advance(r)}
function start(r,log){r.game='uno';r.status='playing';r.unoDeck=deck();r.unoDiscard=[];r.unoDirection=1;r.unoColor=null;r.unoDrawStack=0;r.unoPendingPlay=null;r.unoVulnerable=null;r.unoDrawnCardId=null;r.winner=null;r.winnerId=null;r.players.forEach(p=>{p.unoHand=[];p.unoDrawReadyAt=0;p.unoCalled=false;p.abandoned=false;draw(r,p,7)});r.turn=Math.floor(Math.random()*r.players.length);let first;do{first=r.unoDeck.pop();if(first.type==='wild4')r.unoDeck.unshift(first)}while(first.type==='wild4');r.unoDiscard.push(first);r.unoColor=first.color;r.phase=first.type==='wild'?'unoChooseStartColor':'unoPlay';if(first.type==='draw2'){draw(r,r.players[r.turn],2);advance(r)}else if(first.type==='skip')advance(r);else if(first.type==='reverse'){r.unoDirection=-1;advance(r)}log(r,`Comienza HUGO. ${r.players[r.turn].name} tiene el primer turno.`)}
function publicState(r,playerId){const own=r.players.find(p=>p.id===playerId);return{...r,decks:undefined,offers:undefined,debts:undefined,unoDeckCount:r.unoDeck?.length||0,unoDeck:undefined,unoDiscard:r.unoDiscard?.slice(-12)||[],players:r.players.map(({reconnectToken,connectionId,lastChatAt,unoHand,...p})=>({...p,handCount:unoHand?.length||0})),hand:own?.unoHand||[]}}
function nextAfterRemoval(r,log){const active=activePlayers(r);if(active.length<=1){r.status='finished';r.winner=active[0]?.name||null;r.winnerId=active[0]?.id||null;r.phase='end';log(r,`${r.winner||'Nadie'} gana la partida.`);return}advance(r)}
function skipTurn(r,log){const p=r.players[r.turn];r.unoPendingPlay=null;r.unoDrawStack=0;r.unoVulnerable=null;r.unoDrawnCardId=null;advance(r);log(r,`Se omitió el turno de ${p.name}.`);return true}
function install(io,socket,{rooms,emit,log}){
  socket.on('unoChooseColor',color=>{const r=rooms.get(socket.data.room),p=r?.players[r.turn];if(r?.game!=='uno'||p?.id!==socket.id||r.phase!=='unoChooseStartColor'||!COLORS.includes(color))return;r.unoColor=color;r.phase='unoPlay';log(r,`${p.name} eligió ${COLOR_NAMES[color]} para comenzar.`);emit(r)});
  socket.on('unoCall',acknowledge=>{const reply=(ok,message)=>typeof acknowledge==='function'&&acknowledge({ok,message}),r=rooms.get(socket.data.room),p=r?.players[r.turn],canFinishPlay=p?.unoHand.some(card=>playable(r,card,p)&&(r.phase!=='unoDrawn'||card.id===r.unoDrawnCardId));if(r?.game!=='uno'||r.status!=='playing')return reply(false,'La partida de HUGO no está activa.');if(p?.id!==socket.id)return reply(false,'Todavía no es tu turno.');if(!['unoPlay','unoDrawn'].includes(r.phase))return reply(false,'Ahora no puedes anunciar HUGO.');if(r.unoDrawStack)return reply(false,'Primero debes resolver la penalización +2.');if(p.unoHand.length!==2)return reply(false,'Debes tener exactamente dos cartas.');if(!canFinishPlay)return reply(false,'No tienes una carta que puedas lanzar ahora.');if(p.unoCalled)return reply(true,'HUGO ya estaba anunciado.');p.unoCalled=true;log(r,`${p.name} anunció ¡HUGO!`);emit(r);reply(true,'HUGO anunciado.')});
  socket.on('unoPlay',data=>{const r=rooms.get(socket.data.room),p=r?.players[r.turn],card=p?.unoHand.find(c=>c.id===data?.cardId);if(r?.game!=='uno'||r.status!=='playing'||p?.id!==socket.id||!['unoPlay','unoDrawn'].includes(r.phase)||!card||!playable(r,card,p))return socket.emit('errorMessage','Esa carta no se puede jugar ahora.');const chosenColor=COLORS.includes(data.chosenColor)?data.chosenColor:card.color;if(!chosenColor)return socket.emit('errorMessage','Elige el color que continúa.');const calledUno=Boolean(p.unoCalled||(data?.calledUno&&p.unoHand.length===2&&!r.unoDrawStack));if(calledUno&&!p.unoCalled)log(r,`${p.name} anunció ¡HUGO! al lanzar su carta.`);clearCatchWindow(r);r.unoPendingPlay={playerId:p.id,cardId:card.id,chosenColor,calledUno};resolvePlay(r,log);emit(r)});
  socket.on('unoDraw',()=>{const r=rooms.get(socket.data.room),p=r?.players[r.turn];if(r?.game!=='uno'||p?.id!==socket.id||r.phase!=='unoPlay')return;if(p.unoHand.some(card=>playable(r,card,p)))return socket.emit('errorMessage','Tienes una carta que puedes jugar; no puedes robar.');p.unoCalled=false;clearCatchWindow(r);if(r.unoDrawStack){const count=r.unoDrawStack;r.unoDrawStack=0;draw(r,p,count);log(r,`${p.name} tomó ${count} cartas acumuladas.`);advance(r);return emit(r)}if((p.unoDrawReadyAt||0)>Date.now())return;p.unoDrawReadyAt=Date.now()+650;draw(r,p,1);r.unoDrawnCardId=p.unoHand.at(-1).id;if(playable(r,p.unoHand.at(-1),p)){r.phase='unoDrawn';log(r,`${p.name} tomó una carta y debe jugarla.`)}else{r.unoDrawnCardId=null;r.phase='unoPlay';log(r,`${p.name} tomó una carta que no puede jugar; debe seguir robando.`)}emit(r)});
  socket.on('unoCatch',()=>{const r=rooms.get(socket.data.room),target=r?.players.find(p=>p.id===r.unoVulnerable);if(r?.game!=='uno'||!target||target.id===socket.id)return;draw(r,target,2);r.unoVulnerable=null;log(r,`${target.name} olvidó decir HUGO y tomó dos cartas.`);emit(r)})
}
module.exports={start,publicState,install,nextAfterRemoval,skipTurn};
