const {io}=require('socket.io-client');
const url=process.env.TEST_URL||'http://localhost:3012';
const a=io(url),b=io(url);let code,started=false,played=false,initialCount;
const fail=message=>{console.error(message);a.close();b.close();process.exit(1)};
const timer=setTimeout(()=>fail('UNO smoke: tiempo agotado'),8000);
a.on('connect',()=>a.emit('create',{name:'Ana',game:'uno'}));
a.on('state',state=>{if(!code){code=state.code;if(state.game!=='uno')return fail('La sala no conservó el juego UNO');b.emit('join',{name:'Beto',code})}if(state.players.length===2&&!started){started=true;a.emit('start')}if(state.status==='playing'){if(!initialCount){initialCount=state.hand.length;if(initialCount!==7)return fail('Ana no recibió 7 cartas');if(state.unoDeckCount+state.players.reduce((sum,p)=>sum+p.handCount,0)+state.unoDiscard.length!==108)return fail('El mazo no contiene 108 cartas')}if(state.players.some(player=>'unoHand' in player))return fail('Se filtró una mano privada');if(state.players[state.turn].id===a.id&&state.phase==='unoChooseStartColor')return a.emit('unoChooseColor','red');if(state.players[state.turn].id===a.id&&['unoPlay','unoDrawn'].includes(state.phase)&&!played){const top=state.unoDiscard.at(-1),card=state.hand.find(c=>state.phase==='unoDrawn'?c.id===state.unoDrawnCardId:c.type==='wild'||c.color===state.unoColor||(c.type!=='number'&&c.type===top.type)||(c.type==='number'&&top.type==='number'&&c.value===top.value));if(!card)return setTimeout(()=>a.emit('unoDraw'),700);played=true;a.emit('unoPlay',{cardId:card.id,chosenColor:card.color||'blue',calledUno:false})}if(played&&state.players[state.turn].id!==a.id&&state.hand.length<initialCount+1){clearTimeout(timer);console.log('uno-108-reparto-privacidad-jugada-directa: ok');a.close();b.close();process.exit(0)}}});
b.on('state',state=>{if(state.status!=='playing'||state.players[state.turn].id!==b.id)return;if(state.phase==='unoChooseStartColor')return b.emit('unoChooseColor','red');if(state.phase==='unoPlay')return setTimeout(()=>b.emit('unoDraw'),700);if(state.phase==='unoDrawn'){const card=state.hand.find(item=>item.id===state.unoDrawnCardId);if(card)b.emit('unoPlay',{cardId:card.id,chosenColor:card.color||'blue',calledUno:false})}});
a.on('connect_error',error=>fail(error.message));b.on('connect_error',error=>fail(error.message));
