const {io}=require('socket.io-client');
const url=process.env.TEST_URL||'http://localhost:3012';
const a=io(url),b=io(url);let code,started=false,played=false,voted=false,initialCount;
const fail=message=>{console.error(message);a.close();b.close();process.exit(1)};
const timer=setTimeout(()=>fail('UNO smoke: tiempo agotado'),8000);
a.on('connect',()=>a.emit('create',{name:'Ana',game:'uno'}));
a.on('state',state=>{if(!code){code=state.code;if(state.game!=='uno')return fail('La sala no conservó el juego UNO');b.emit('join',{name:'Beto',code})}if(state.players.length===2&&!started){started=true;a.emit('start')}if(state.status==='playing'){if(!initialCount){initialCount=state.hand.length;if(initialCount!==7)return fail('Ana no recibió 7 cartas');if(state.unoDeckCount+state.players.reduce((sum,p)=>sum+p.handCount,0)+state.unoDiscard.length!==108)return fail('El mazo no contiene 108 cartas')}if(state.players.some(player=>'unoHand' in player))return fail('Se filtró una mano privada');if(state.players[state.turn].id===a.id&&state.phase==='unoChooseStartColor')return a.emit('unoChooseColor','red');if(state.players[state.turn].id===a.id&&['unoPlay','unoDrawn'].includes(state.phase)&&!played){const top=state.unoDiscard[0],card=state.hand.find(c=>state.phase==='unoDrawn'?c.id===state.unoDrawnCardId:c.type==='wild'||c.color===state.unoColor||c.type===top.type||(c.type==='number'&&top.type==='number'&&c.value===top.value));if(!card)return state.phase==='unoDrawn'?a.emit('unoPass'):a.emit('unoDraw');played=true;a.emit('unoPlay',{cardId:card.id,chosenColor:card.color||'blue',phrase:'Hay un libro ahí. ¡Ay, olvidé leerlo!',calledUno:false})}if(played&&state.players[state.turn].id!==a.id&&state.hand.length<initialCount+1){clearTimeout(timer);console.log('uno-108-reparto-privacidad-jugada: ok');a.close();b.close();process.exit(0)}}});
b.on('state',state=>{if(state.phase==='unoReview'&&!voted&&state.unoPendingPlay?.playerId===a.id){voted=true;return b.emit('unoVote',true)}if(state.status==='playing'&&state.players[state.turn].id===b.id){if(state.phase==='unoChooseStartColor')b.emit('unoChooseColor','red');else if(state.phase==='unoPlay')b.emit('unoDraw');else if(state.phase==='unoDrawn')b.emit('unoPass')}});
a.on('connect_error',error=>fail(error.message));b.on('connect_error',error=>fail(error.message));
